backend = "fastresize"
color_space = "labmixed"
palette = "dark"

[templates]
theme_colors = { template = 'kitty.conf', target = '~/.cache/theme/kitty/colors.conf' }
firefox = { template = 'userChrome.css', target = '~/.mozilla/firefox/squirrel/chrome/userChrome.css' }
hyprland_colors = { template = 'hyprland-colors.lua', target = '~/.cache/theme/hyprland/colors.lua' }
quickshell_colors = { template = 'quickshell-colors.json', target = '~/.cache/theme/quickshell/colors.json' }
