#!/usr/bin/env bash

printwindow() {
    input=$(hyprctl activewindow | grep -oP '(?<=title: )[^ ].*')

    if [[ ! -z "$input" ]]; then
        echo $input
    fi
}

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r event; do
    printwindow $event
done